número1 = int(input("Qual o primeiro número?"))
número2 = int(input("Qual o segundo número?"))
multiplicação = (número1 * número2)
print(f'multiplicação é {multiplicação}')
divisão = (número1/número2)
print(f'divisão é {divisão}')
subtração = (número1-número2)
print(f'subtração é {subtração}')
adição = (número1+número2)
print(f'adição é {adição}')